<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedBigInteger('parish_id')->nullable();
            $table->timestamps();
            $table->foreign('parish_id')->references('id')->on('parishes')->onDelete('set null');
        });

        DB::table('cities')->insert([
            ['name' => "Kingston",'parish_id' => "1"],
            ['name' => "Tivoli Gardens",'parish_id' => "1"],
            ['name' => "Denham Town",'parish_id' => "1"],
            ['name' => "Rae Town",'parish_id' => "1"],
            ['name' => "Kingston Gardens",'parish_id' => "1"],
            ['name' => "National Heroes Park",'parish_id' => "1"],
            ['name' => "Bournemouth Gardens",'parish_id' => "1"],
            ['name' => "Norman Gardens",'parish_id' => "1"],
            ['name' => "Rennock Lodge",'parish_id' => "1"],
            ['name' => "Springfield",'parish_id' => "1"],
            ['name' => "Port Royal",'parish_id' => "1"],
            ['name' => "Constant Spring",'parish_id' => "2"],
            ['name' => "Gordon Town",'parish_id' => "2"],
            ['name' => "Mavis Bank",'parish_id' => "2"],
            ['name' => "Stony Hill",'parish_id' => "2"],
            ['name' => "Bull Bay",'parish_id' => "2"],
            ['name' => "Hopewell",'parish_id' => "2"],
            ['name' => "Mavis Bank",'parish_id' => "2"],
            ['name' => "Arnett Gardens",'parish_id' => "2"],
            ['name' => "Allman Town",'parish_id' => "2"],
            ['name' => "August Town",'parish_id' => "2"],
            ['name' => "Barbican",'parish_id' => "2"],
            ['name' => "Beverly Hills",'parish_id' => "2"],
            ['name' => "Bumper Hall",'parish_id' => "2"],
            ['name' => "Bull Bay",'parish_id' => "2"],
            ['name' => "Callaloo Bed",'parish_id' => "2"],
            ['name' => "Cassia Park",'parish_id' => "2"],
            ['name' => "Constant Spring",'parish_id' => "2"],
            ['name' => "Cassava Piece",'parish_id' => "2"],
            ['name' => "Chancery Heights",'parish_id' => "2"],
            ['name' => "Cherry Gardens",'parish_id' => "2"],
            ['name' => "Cypress Hall",'parish_id' => "2"],
            ['name' => "Cockburn Penn",'parish_id' => "2"],
            ['name' => "Cooper's Hill",'parish_id' => "2"],
            ['name' => "Denham Town",'parish_id' => "2"],
            ['name' => "Duhaney Park",'parish_id' => "2"],
            ['name' => "Drew's Land",'parish_id' => "2"],
            ['name' => "Elliston Flat",'parish_id' => "2"],
            ['name' => "Fletcher's Land",'parish_id' => "2"],
            ['name' => "Franklin Town",'parish_id' => "2"],
            ['name' => "Golden Spring",'parish_id' => "2"],
            ['name' => "Gordon Town",'parish_id' => "2"],
            ['name' => "Grant's Pen",'parish_id' => "2"],
            ['name' => "Greenwich Town",'parish_id' => "2"],
            ['name' => "Guava Gap",'parish_id' => "2"],
            ['name' => "Hannah Town",'parish_id' => "2"],
            ['name' => "Harbor View",'parish_id' => "2"],
            ['name' => "Havendale",'parish_id' => "2"],
            ['name' => "Independence Park",'parish_id' => "2"],
            ['name' => "Irish Town",'parish_id' => "2"],
            ['name' => "Jacks Hill",'parish_id' => "2"],
            ['name' => "Jungle",'parish_id' => "2"],
            ['name' => "Jones Town",'parish_id' => "2"],
            ['name' => "Kingweston",'parish_id' => "2"],
            ['name' => "King Wood",'parish_id' => "2"],
            ['name' => "Lawrence Tavern",'parish_id' => "2"],
            ['name' => "Manning's Hill",'parish_id' => "2"],
            ['name' => "Marverly",'parish_id' => "2"],
            ['name' => "Meadowbrook",'parish_id' => "2"],
            ['name' => "Mount James",'parish_id' => "2"],
            ['name' => "Mount Salus",'parish_id' => "2"],
            ['name' => "Nannyville",'parish_id' => "2"],
            ['name' => "New Kingston",'parish_id' => "2"],
            ['name' => "New Castle",'parish_id' => "2"],
            ['name' => "Norbrook",'parish_id' => "2"],
            ['name' => "Olympic Gardens",'parish_id' => "2"],
            ['name' => "Paine Land",'parish_id' => "2"],
            ['name' => "Patrick City",'parish_id' => "2"],
            ['name' => "Pear Hill",'parish_id' => "2"],
            ['name' => "Pembroke Hall",'parish_id' => "2"],
            ['name' => "Papine",'parish_id' => "2"],
            ['name' => "Queensbury",'parish_id' => "2"],
            ['name' => "Red Gal Ring",'parish_id' => "2"],
            ['name' => "Rollington Town",'parish_id' => "2"],
            ['name' => "Riverton City",'parish_id' => "2"],
            ['name' => "Rockfort",'parish_id' => "2"],
            ['name' => "Seaview Gardens",'parish_id' => "2"],
            ['name' => "Shooters Hill",'parish_id' => "2"],
            ['name' => "Six Miles",'parish_id' => "2"],
            ['name' => "Smoky Vale",'parish_id' => "2"],
            ['name' => "Stony Hill",'parish_id' => "2"],
            ['name' => "Strawberry Hill",'parish_id' => "2"],
            ['name' => "Tinson Pen",'parish_id' => "2"],
            ['name' => "Tivoli Gardens",'parish_id' => "2"],
            ['name' => "Trenchtown",'parish_id' => "2"],
            ['name' => "Tower Hill",'parish_id' => "2"],
            ['name' => "Temple Hall",'parish_id' => "2"],
            ['name' => "Unity",'parish_id' => "2"],
            ['name' => "Vineyard Town",'parish_id' => "2"],
            ['name' => "Washington Garden",'parish_id' => "2"],
            ['name' => "Waterhouse",'parish_id' => "2"],
            ['name' => "Warekia Hill",'parish_id' => "2"],
            ['name' => "Whitehall",'parish_id' => "2"],
            ['name' => "Wilton Garden",'parish_id' => "2"],
            ['name' => "Ziadie Gardens",'parish_id' => "2"],
            ['name' => "Port Antonio",'parish_id' => "3"],
            ['name' => "Buff Bay",'parish_id' => "3"],
            ['name' => "Hope Bay",'parish_id' => "3"],
            ['name' => "Manchioneal",'parish_id' => "3"],
            ['name' => "Moore Town",'parish_id' => "3"],
            ['name' => "Cattawood Springs",'parish_id' => "3"],
            ['name' => "Nanny Town",'parish_id' => "3"],
            ['name' => "San San",'parish_id' => "3"],
            ['name' => "Morant Bay",'parish_id' => "4"],
            ['name' => "Bath",'parish_id' => "4"],
            ['name' => "Dalvey",'parish_id' => "4"],
            ['name' => "Easington",'parish_id' => "4"],
            ['name' => "Golden Grove",'parish_id' => "4"],
            ['name' => "Morant Bay",'parish_id' => "4"],
            ['name' => "Seaforth",'parish_id' => "4"],
            ['name' => "Trinity Ville",'parish_id' => "4"],
            ['name' => "Yallahs",'parish_id' => "4"],
            ['name' => "Aeolus Valley",'parish_id' => "4"],
            ['name' => "Airy Castle",'parish_id' => "4"],
            ['name' => "Barking Lodge",'parish_id' => "4"],
            ['name' => "Duckenfield",'parish_id' => "4"],
            ['name' => "Hagley Gap",'parish_id' => "4"],
            ['name' => "Hopewell Hall",'parish_id' => "4"],
            ['name' => "Lloyds",'parish_id' => "4"],
            ['name' => "Port Morant",'parish_id' => "4"],
            ['name' => "Portmore",'parish_id' => "5"],
            ['name' => "Spanish Town",'parish_id' => "5"],
            ['name' => "Old Harbour",'parish_id' => "5"],
            ['name' => "Linstead",'parish_id' => "5"],
            ['name' => "Above Rocks",'parish_id' => "5"],
            ['name' => "Bog Walk",'parish_id' => "5"],
            ['name' => "Ewarton",'parish_id' => "5"],
            ['name' => "Lluidas Vale",'parish_id' => "5"],
            ['name' => "Old Harbour Bay",'parish_id' => "5"],
            ['name' => "Point Hill",'parish_id' => "5"],
            ['name' => "Riversdale",'parish_id' => "5"],
            ['name' => "Wood Hall",'parish_id' => "5"],
            ['name' => "Annotto Bay",'parish_id' => "6"],
            ['name' => "Gayle",'parish_id' => "6"],
            ['name' => "Guy's Hill",'parish_id' => "6"],
            ['name' => "Highgate",'parish_id' => "6"],
            ['name' => "Islington",'parish_id' => "6"],
            ['name' => "Lucky Hill",'parish_id' => "6"],
            ['name' => "Oracabessa",'parish_id' => "6"],
            ['name' => "Port Maria",'parish_id' => "6"],
            ['name' => "Richmond",'parish_id' => "6"],
            ['name' => "Boscobel",'parish_id' => "6"],
            ['name' => "Haddersfield",'parish_id' => "6"],
            ['name' => "Ocho Rios",'parish_id' => "7"],
            ['name' => "Saint Ann's Bay",'parish_id' => "7"],
            ['name' => "Alexandria",'parish_id' => "7"],
            ['name' => "Bamboo",'parish_id' => "7"],
            ['name' => "Brown's Town",'parish_id' => "7"],
            ['name' => "Cave Valley",'parish_id' => "7"],
            ['name' => "Claremont",'parish_id' => "7"],
            ['name' => "Discovery Bay (Dry Harbour)",'parish_id' => "7"],
            ['name' => "Moneague",'parish_id' => "7"],
            ['name' => "Ocho Rios",'parish_id' => "7"],
            ['name' => "Runaway Bay",'parish_id' => "7"],
            ['name' => "Hopewell",'parish_id' => "7"],
            ['name' => "Nine Mile",'parish_id' => "7"],
            ['name' => "Mandeville",'parish_id' => "8"],
            ['name' => "Alligator Pond",'parish_id' => "8"],
            ['name' => "Christiana",'parish_id' => "8"],
            ['name' => "Coleyville",'parish_id' => "8"],
            ['name' => "Porus",'parish_id' => "8"],
            ['name' => "Williamsfield",'parish_id' => "8"],
            ['name' => "Hopewell",'parish_id' => "8"],
            ['name' => "Meadsfiedl",'parish_id' => "8"],
            ['name' => "Roxborough",'parish_id' => "8"],
            ['name' => "May Pen",'parish_id' => "9"],
            ['name' => "Hayes",'parish_id' => "9"],
            ['name' => "Chapelton",'parish_id' => "9"],
            ['name' => "Croft's Hill",'parish_id' => "9"],
            ['name' => "Frankfield",'parish_id' => "9"],
            ['name' => "Kellits",'parish_id' => "9"],
            ['name' => "Lionel Town",'parish_id' => "9"],
            ['name' => "Osbourne Store",'parish_id' => "9"],
            ['name' => "Race Course",'parish_id' => "9"],
            ['name' => "Rocky Point",'parish_id' => "9"],
            ['name' => "Sanguinetti",'parish_id' => "9"],
            ['name' => "Spalding",'parish_id' => "9"],
            ['name' => "Clarendon Park",'parish_id' => "9"],
            ['name' => "Hopewell",'parish_id' => "9"],
            ['name' => "Cascade",'parish_id' => "10"],
            ['name' => "Green Island",'parish_id' => "10"],
            ['name' => "Hopewell",'parish_id' => "10"],
            ['name' => "Lucea",'parish_id' => "10"],
            ['name' => "Sandy Bay",'parish_id' => "10"],
            ['name' => "Savanna-la-Mar",'parish_id' => "11"],
            ['name' => "Bethel Town",'parish_id' => "11"],
            ['name' => "Bluefields",'parish_id' => "11"],
            ['name' => "Darliston",'parish_id' => "11"],
            ['name' => "Frome",'parish_id' => "11"],
            ['name' => "Grange Hill",'parish_id' => "11"],
            ['name' => "Little London",'parish_id' => "11"],
            ['name' => "Negril",'parish_id' => "11"],
            ['name' => "Petersfield",'parish_id' => "11"],
            ['name' => "Seaford Town",'parish_id' => "11"],
            ['name' => "White House",'parish_id' => "11"],
            ['name' => "Bog",'parish_id' => "11"],
            ['name' => "Big Woods",'parish_id' => "11"],
            ['name' => "Hopewell",'parish_id' => "11"],
            ['name' => "Hopeton",'parish_id' => "11"],
            ['name' => "Carmel",'parish_id' => "11"],
            ['name' => "Montego Bay",'parish_id' => "12"],
            ['name' => "Anchovy",'parish_id' => "12"],
            ['name' => "Cambridge",'parish_id' => "12"],
            ['name' => "Maroon Town",'parish_id' => "12"],
            ['name' => "Albert Town",'parish_id' => "13"],
            ['name' => "Clark's Town",'parish_id' => "13"],
            ['name' => "Duncans",'parish_id' => "13"],
            ['name' => "Falmouth",'parish_id' => "13"],
            ['name' => "Rio Bueno",'parish_id' => "13"],
            ['name' => "Ulster Spring",'parish_id' => "13"],
            ['name' => "Wakefield",'parish_id' => "13"],
            ['name' => "Balaclava",'parish_id' => "14"],
            ['name' => "Black River",'parish_id' => "14"],
            ['name' => "Brompton",'parish_id' => "14"],
            ['name' => "Bull Savanna",'parish_id' => "14"],
            ['name' => "Lacovia",'parish_id' => "14"],
            ['name' => "Maggotty",'parish_id' => "14"],
            ['name' => "Malvern",'parish_id' => "14"],
            ['name' => "Nain",'parish_id' => "14"],
            ['name' => "Santa Cruz",'parish_id' => "14"],
            ['name' => "Siloah",'parish_id' => "14"],
            ['name' => "Southfield",'parish_id' => "14"],
            ['name' => "Accompong",'parish_id' => "14"],
            ['name' => "Cotterwood",'parish_id' => "14"],
            ['name' => "Hodges",'parish_id' => "14"],
            ['name' => "Hopewell",'parish_id' => "14"],
            ['name' => "Long Wood",'parish_id' => "14"],
            ['name' => "Middle Quarters",'parish_id' => "14"],
            ['name' => "New Holland",'parish_id' => "14"],
            ['name' => "New Market",'parish_id' => "14"],
            ['name' => "New Roads",'parish_id' => "14"],
            ['name' => "Paynes Town",'parish_id' => "14"],
            ['name' => "White Hall",'parish_id' => "14"]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}
